language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: leclerev-github
# command to run tests
script:
  - pytest -v --cov .
  #- sonar-scanner
  #- coveralls
